# Generated by Django 2.0.2 on 2018-02-26 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_description', models.TextField(blank=True, default='Our revolutionary product will change the world', help_text='Product Pitch in less than 280 character', max_length=280, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('no_spam', models.BooleanField(default=False)),
                ('website', models.URLField(help_text='Your Landing page URL. When you choose to advert, your advert will divert to this URL.', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
