# Generated by Django 2.0.2 on 2018-03-03 08:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180226_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
