# Generated by Django 2.0.2 on 2018-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180303_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hire_me_if_want',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
