# Generated by Django 2.0.2 on 2018-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180310_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Updated_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
