# Generated by Django 2.0.2 on 2018-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180421_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='redirect_count',
            field=models.IntegerField(default=0),
        ),
    ]
